### ISSUE TITLE
Importing favorites. 

### ISSUE THREAD

**Issue by Cone2** [DontTalkToMeThx/BooruSlideshowElectron#5]
Unsure if this is the right place to put this, but I'd like to take my favorites from the Booruslideshow extension on Firefox and put them on the electron app. How would I go about doing so?

**Comment by DontTalkToMeThx** [comment]
This is a tricky question, but I can give you a general run down of how you could do it.

First, the electron app stores all your data in the appdata folder, you can access this by going to your file explorer, and in the current folder, type `%appdata%`. There will be many apps in there, but  you are looking for a folder called `booruslideshowelectron` (alternatively, use `%appdata%/booruslideshowelectron`) 

In this folder, are many caches and session storages to enhance performance, but you want to find the `storage` folder, there will be many JSON files in there (mainly due to my bad coding) but you'll find one called `personalListItems.json` open it. In there delete everything (Ctrl + A -> backspace) paste this exactly: `{"personalListItems":}`

Now, open the extension, press `ctrl + shift + i` to open the dev console, and because firefox is very compatible, you can run this code that also works for the chrome extension:
```
chrome.storage.local.get(['personalListItems'],
function (data) {
    var blob = new Blob([JSON.stringify(data.personalListItems)], {type: 'text/json'}),
        e    = document.createEvent('MouseEvents'),
        a    = document.createElement('a')

    a.download = "listItems.json"
    a.href = window.URL.createObjectURL(blob)
    a.dataset.downloadurl =  ['text/json', a.download, a.href].join(':')
    e.initMouseEvent('click', true, false, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null)
    a.dispatchEvent(e)
})
```
This will download the favorites list from the extension.

After you do that, open the file, copy the contents onto your clipboard (ctrl + A -> ctrl + c). Go back into the personalListItems.json you opened and edited, **after the colon (`:`) paste the contents** this should be before the ending curly bracket `}` but after the colon.

You should end up with a file that looks like this:
```
{"personalListItems":[{"siteId":"SAFE","id":"3140487","fileUrl":"https://safebooru.org/images/3016/e911d5036c025c082280a60f023ac1c0.jpeg","previewFileUrl":"https://safebooru.org/images/3016/e911d5036c025c082280a60f023ac1c0.jpeg","viewableWebsitePostUrl":"https://safebooru.org/index.php?page=post&s=view&id=3140487","width":"517","height":"769","date":"2020-07-16T10:42:12.000Z","score":"","mediaType":"IMAGE","md5":"e911d5036c025c082280a60f023ac1c0","isPreloaded":false,"isPreloading":false,"preloadingImage":null,"preloadingVideo":null,"callbackToRunAfterPreloadingFinishes":null,"tags":"1girl 2014 :o absurdres blue_swimsuit blush brown_hair collarbone covered_navel female futsuu_no_joshikousei_ga_locodol_yattemita hand_on_hip name_tag pose scan school_swimsuit short_hair solo usami_nanako violet_eyes w"}]}
```
but probably much larger.
